# конфигурация базы данных PostgreSQL
postgres:
  host: "postgres"
  port: 5432
  username: "avito-user"
  password: "avito-password"
  database: "avito"
  max_conns: 10
  min_conns: 5

# конфигурация PR сервиса
pr:
  host: avito-service
  port: 8080
